version: 2.1
jobs:
 build:
   docker:
     - image: circleci/node:10.16.3
   steps:
     - checkout
     - run:
         paths: 
          - ./frontend
         name: Update NPM
         command: "sudo npm install -g npm@5"
     - restore_cache:
         key: dependency-cache-{{ checksum "package-lock.json" }}
     - run:
         paths: 
          - ./frontend
         name: Install Dependencies
         command: npm install
     - save_cache:
     
         key: dependency-cache-{{ checksum "package-lock.json" }}
         paths:
           - ./frontend/node_modules
     - run:
         name: Run tests
         command: npm run test